#ifndef TURADOR_TURA_UI_PURCHASECARGOINPUTCOMMAND_HPP_INCLUDED
#define TURADOR_TURA_UI_PURCHASECARGOINPUTCOMMAND_HPP_INCLUDED

namespace tura
{
namespace ui
{
class PurchaseCargoInputCommand
{
};
}
}

#endif // #ifndef TURADOR_TURA_UI_PURCHASECARGOINPUTCOMMAND_HPP_INCLUDED
